import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import ModeToggle from "@/app/components/modeToggle";
import Navbar from "@/app/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hikaru's Domain",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black dark:bg-[#212529] dark:text-white transition duration-500`}
    >
    <main className="px-64">
      {/* Navbar */}
      <nav className="fixed top-5 left-1/2 -translate-x-1/2 text-white bg-[#495057] shadow-md px-8 py-3 rounded-full flex gap-28 items-center font-medium backdrop-blur-sm z-50">
        <h1 className="text-xl font-bold h-7 w-44 items-center justify-center cursor-default">
          Hikaru&apos;s Domain
        </h1>

        <Navbar />

        <ModeToggle />
      </nav>

      {/* Main Content */}
      {children}

      <footer className="fixed bottom-2 w-[62.5vw] text-center text-sm text-neutral-500">
        2025 Copyright Hikaru
      </footer>
    </main>
    </body>
    </html>
  );
}
